package com.iz.pojo;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

@Getter
@Setter
public class UserInfo implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * iz_user.id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * iz_user.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * iz_user.sex
   *
   * @mbggenerated
   */
  private String sex;
}
